### ISSUE TITLE
Stuff to add! :D

### ISSUE THREAD

**Issue by dabomb69** [excid3/logbot#1]
<Chazz> Can you add topic changes, mode changes, parts, and quits? :P
<Chazz> and nick changes
<Chazz> What else happens in a channel?
<Chazz> /notice
<Chazz> and
<Chazz> (And add in the nickserv stuff so i don't have to rehard code it in :P)
<Chazz> (And oper would be cool too, but 99% of people wouldn't use that xP)

**Comment by excid3** [comment]
All issues fixed. Oper won't be added to the logbot. Identification works as well as all the other IRC event logging.
