### ISSUE TITLE
Crash upon accessing files in empty log dir

### ISSUE THREAD

**Issue by unsolaci** [excid3/logbot#2]
If you create an **empty** directory for logs by hand, and then point the bot to it, it crashes. I think it only checks if the directory exists, then tries to access non-existing files(i.e. logs/index.html).

**Comment by excid3** [comment]
Little bit on the laziness side for me, but I'll patch it as soon as I can, might be the beginning of the next week at the earliest though. Midterms this coming week!

**Comment by excid3** [comment]
Should be fixed. Pushed the latest code with a bugfix but I didn't create a new download for it so you will have to checkout with git.

**Comment by unsolaci** [comment]
Yup. This works fine now.
